### ISSUE TITLE
能否提供一下pheme数据集，非常感谢

### ISSUE THREAD

**Issue by findmi** [Coder-HenryZa/RDSPU#1]
看您dataset数据集里面缺少pheme的数据，是否可以提供一下，非常感谢。

**Comment by Coder-HenryZa** [comment]
Due to privacy protection, PHEME's data cannot be shared publicly. Please leave your email address and I will send it to you later.

**Comment by findmi** [comment]
> Due to privacy protection, PHEME's data cannot be shared publicly. Please leave your email address and I will send it to you later.

865045540@qq.com
非常感谢

**Comment by Gsuhy-L** [comment]
Hello, can you share the Pheme's data? If the data format can be similar to TwitterXX_Statuses.csv, I would greatly appreciate it. My meail is gsuhyl@qq.com.

**Comment by zzw786** [comment]
您好，现在是否还可以提供您的pheme数据集，非常感谢！我的邮箱是445865987@qq.com
